# -*- coding: utf-8 -*-
"""
/***************************************************************************
 moja_wtyczka_QGIS
                                 A QGIS plugin
 Wtyczka liczy różnice wysokości oraz pole pomiedzy punktami
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-04
        copyright            : (C) 2023 by Mikolaj Grabarczyk
        email                : 01159852@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load moja_wtyczka_QGIS class from file moja_wtyczka_QGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wtyczka_QGIS import moja_wtyczka_QGIS
    return moja_wtyczka_QGIS(iface)
