# -*- coding: utf-8 -*-
"""
/***************************************************************************
 moja_wtyczka_QGISDialog
                                 A QGIS plugin
 Wtyczka liczy różnice wysokości oraz pole pomiedzy punktami
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-04
        copyright            : (C) 2023 by Mikolaj Grabarczyk
        email                : 01159852@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.utils import iface
from qgis.core import QgsWkbTypes
import numpy as np
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QDialog, QApplication, QMessageBox

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'wtyczka_QGIS_dialog_base.ui'))

class moja_wtyczka_QGISDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(moja_wtyczka_QGISDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.radioButton.clicked.connect(self.calck)
        self.radioButton_2.clicked.connect(self.calck)
        
        
    def calck(self):
        aw = iface.activeLayer()
        lob = aw.selectedFeatureCount()        
        nr = []
        x  = []
        y  = []
        h  = []                       
        for punkt in aw.selectedFeatures():
            x.append(punkt['x92'])
            y.append(punkt['y92'])
            h.append(punkt['h']) 
            nr.append(punkt['nr'])               
            
        if self.radioButton.isChecked() == True and lob == 2:             
            dh = h[1] - h[0]
            PK1 = nr[0]
            PK2 = nr[1]
            iface.messageBar().pushMessage('Różnica wysokosci między punktem '+ str(PK1)+ ' oraz punktem '+str(PK2) + ' to: '+str(round(dh,3))+' |m|')
        
        elif self.radioButton_2.isChecked() == True and lob > 2: 
            pts = []
            for i in range(0, len(x)):
                pts.append([x[i], y[i]])        
            pa = 0
            for i in range(len(pts)):
                if i == len(pts)-1:
                    pa += (pts[i][0] + pts[0][0]) * (pts[i][1] - pts[0][1])
                else: 
                    pa += (pts[i][0] + pts[i+1][0]) * (pts[i][1] - pts[i+1][1])                
            P = -pa/2
            print(P)          
            iface.messageBar().pushMessage('Pole wybranego obszaru ' + str(nr)+ ' wynosi: '+str(round(P,5))+' |m2|')
       
        else:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText('Zła liczba zaznaczonych punktów do tej operacji!')
            msg.setInformativeText
            msg.setWindowTitle("Błąd przy zaznaczaniu punktów!!")
            msg.exec_()
        
   
         
    
